### ISSUE TITLE
Problem of system font detection with gdtools::font_family_exists ?

### ISSUE THREAD

**Issue by BriceNocenti** [davidgohel/gdtools#61] opened 2021-04-23 08:32 UTC
Hi, 

I’ve got a problem with some fonts in `ggiraph`, namely "DejaVu Sans Condensed" : it works in the tooltips with css, but not as the general font for text elements in the plot itself (set with the `fonts` argument of `girafe`, passed to `dsvg`). And in fact, I don’t find it with `gdtools::font_family_exists("DejaVu Sans Condensed")`. With `gdtools::sys_fonts()`, I found something interesting : "DejaVu Sans Condensed" exists, but the "family" name is simply "Deja Vu Sans", and the "Condensed" part went to "style" (while on the medatada of this font in my computer, using Windows, the font family name is "DejaVu Sans Condensed"). I don’t know if it’s normal behavior (then, where to specify the Condensed style to use it in ggiraph ?), or if it’s a problem with the system font detection algorithm. If I’m not clear, I can also open a subject is StackOverflow with reproducible code. 

Thanks,

**Comment by davidgohel** [comment] 2021-04-23 08:48
Hi,

Without reproducible example, it's hard to help. 

I assume you read https://davidgohel.github.io/ggiraph/articles/offcran/customizing.html#fonts-1

Did you really run `gdtools::font_family_exists("DejaVu Sans Condensed ")` or is it a typo (`gdtools::font_family_exists("DejaVu Sans Condensed")`)?

**Comment by BriceNocenti** [comment] 2021-04-23 10:21
Hi, 

Yes, I had red the page you mention, but still cannot manage to make the font work (and this was indeed a typo in my former post). To be more accurate, I created an example on StackOverflow : 
[https://stackoverflow.com/questions/67228154/ggiraph-problem-of-system-font-detection-with-gdtoolsfont-family-exists ](https://stackoverflow.com/questions/67228154/ggiraph-problem-of-system-font-detection-with-gdtoolsfont-family-exists )

**Comment by davidgohel** [comment] 2021-04-23 10:41
Thanks, I can reproduce now

This is a minimal reprex. While systemfonts find the font, gdtools doesn't.

``` r
systemfonts::match_font("DejaVu Sans Condensed", bold = TRUE)
#> $path
#> [1] "/Users/davidgohel/Library/Fonts/DejaVuSansCondensed-Bold.ttf"
#> 
#> $index
#> [1] 0
#> 
#> $features
#> NULL
gdtools::font_family_exists("DejaVu Sans Condensed")
#> [1] FALSE
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       macOS  10.16                
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  fr_FR.UTF-8                 
#>  ctype    fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2021-04-23                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version   date       lib source                            
#>  backports     1.2.1     2020-12-09 [1] CRAN (R 4.0.2)                    
#>  cli           2.4.0     2021-04-05 [1] CRAN (R 4.0.2)                    
#>  crayon        1.4.1     2021-02-08 [1] CRAN (R 4.0.2)                    
#>  digest        0.6.27    2020-10-24 [1] CRAN (R 4.0.2)                    
#>  ellipsis      0.3.1     2020-05-15 [1] CRAN (R 4.0.0)                    
#>  evaluate      0.14      2019-05-28 [1] CRAN (R 4.0.0)                    
#>  fansi         0.4.2     2021-01-15 [1] CRAN (R 4.0.2)                    
#>  fs            1.5.0     2020-07-31 [1] CRAN (R 4.0.2)                    
#>  gdtools       0.2.3.001 2021-01-06 [1] local                             
#>  glue          1.4.2     2020-08-27 [1] CRAN (R 4.0.2)                    
#>  highr         0.9       2021-04-16 [1] CRAN (R 4.0.2)                    
#>  htmltools     0.5.1.1   2021-01-22 [1] CRAN (R 4.0.2)                    
#>  knitr         1.32      2021-04-14 [1] CRAN (R 4.0.2)                    
#>  lifecycle     1.0.0     2021-02-15 [1] CRAN (R 4.0.2)                    
#>  magrittr      2.0.1     2020-11-17 [1] CRAN (R 4.0.2)                    
#>  pillar        1.6.0     2021-04-13 [1] CRAN (R 4.0.2)                    
#>  pkgconfig     2.0.3     2019-09-22 [1] CRAN (R 4.0.0)                    
#>  purrr         0.3.4     2020-04-17 [1] CRAN (R 4.0.0)                    
#>  Rcpp          1.0.6     2021-01-15 [1] CRAN (R 4.0.2)                    
#>  reprex        2.0.0     2021-04-02 [1] CRAN (R 4.0.2)                    
#>  rlang         0.4.10    2020-12-30 [1] CRAN (R 4.0.2)                    
#>  rmarkdown     2.7.3     2021-03-10 [1] Github (rstudio/rmarkdown@61db7a9)
#>  sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 4.0.0)                    
#>  stringi       1.5.3     2020-09-09 [1] CRAN (R 4.0.2)                    
#>  stringr       1.4.0     2019-02-10 [1] CRAN (R 4.0.0)                    
#>  styler        1.4.1     2021-03-30 [1] CRAN (R 4.0.2)                    
#>  systemfonts   1.0.1     2021-02-09 [1] CRAN (R 4.0.2)                    
#>  tibble        3.1.1     2021-04-18 [1] CRAN (R 4.0.2)                    
#>  utf8          1.2.1     2021-03-12 [1] CRAN (R 4.0.2)                    
#>  vctrs         0.3.7     2021-03-29 [1] CRAN (R 4.0.2)                    
#>  withr         2.4.2     2021-04-18 [1] CRAN (R 4.0.2)                    
#>  xfun          0.22      2021-03-11 [1] CRAN (R 4.0.2)                    
#>  yaml          2.2.1     2020-02-01 [1] CRAN (R 4.0.0)                    
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by BriceNocenti** [comment] 2021-04-23 11:01
Thanks, 

On my computer neither `systemfonts::match_font` and `gdtools::font_family_exists`  can find the "DejaVu Sans Condensed" font (but both find "DejaVu Sans") : 
``` r
systemfonts::match_font("DejaVu Sans Condensed", bold = TRUE)
 # $path
 # [1] "C:\\Windows\\Fonts\\arialbd.ttf"
 # 
 # $index
 # [1] 0
 # 
 # $features
 # NULL
gdtools::font_family_exists("DejaVu Sans Condensed")
# [1] FALSE
```

**Comment by davidgohel** [comment] 2021-04-23 12:17
I am not sure if it's a bug. 

https://www.fontsquirrel.com/fonts/dejavu-sans

It seems to me "Condensed" is a feature, as Bold, Italic and Bold italic. (ggplot2 and R graphics only manages normal, bold, italic and bold-italic). 

There is some work planned on ggiraph to make font usage easier.

**Comment by davidgohel** [comment] 2021-04-23 12:26
I am closing the issue as to me, it's not a bug. 

gdtools let you know he can't find a font family named "DejaVu Sans Condensed" because only family "DejaVu Sans" exists.

I will re-open if necessary, but I think that's the correct answer.

**Comment by BriceNocenti** [comment] 2021-04-23 12:26
Yes, it seems to be a feature of the font : but the strange thing, then, it that it works with `ggplot2` and `ggiraph`’s tooltips. For now I will find a workaround, like creating a font with a different name. Thanks for developping `ggiraph`, it’s a powerful tool !

**Closed by davidgohel** 2021-04-23 12:26 UTC
Labels: bug
